version: '3.3'

services:
  report_frontend:
    image: docker.waithakasam.tech/idrisfallout/report_frontend:1.0
    container_name: report_frontend
    restart: unless-stopped
    networks:
      - nginxproxymanager_network

networks:
  nginxproxymanager_network:
    external: true